import {keyByForLoop} from '../utils/util.js';

export const COUNTRY_CODES = [
  {
    name: 'Afghanistan',
    alpha2: 'AF',
    alpha3: 'AFG',
    numeric: 4,
    dialCode: 93,
  },
  {
    name: 'Aland Islands',
    alpha2: 'AX',
    alpha3: 'ALA',
    numeric: 248,
    dialCode: 358,
  },
  {
    name: 'Albania',
    alpha2: 'AL',
    alpha3: 'ALB',
    numeric: 8,
    dialCode: 355,
  },
  {
    name: 'Algeria',
    alpha2: 'DZ',
    alpha3: 'DZA',
    numeric: 12,
    dialCode: 213,
  },
  {
    name: 'American Samoa',
    alpha2: 'AS',
    alpha3: 'ASM',
    numeric: 16,
    dialCode: '1-684',
  },
  {
    name: 'Andorra',
    alpha2: 'AD',
    alpha3: 'AND',
    numeric: 20,
    dialCode: 376,
  },
  {
    name: 'Angola',
    alpha2: 'AO',
    alpha3: 'AGO',
    numeric: 24,
    dialCode: 244,
  },
  {
    name: 'Anguilla',
    alpha2: 'AI',
    alpha3: 'AIA',
    numeric: 660,
    dialCode: '1-264',
  },
  {
    name: 'Antarctica',
    alpha2: 'AQ',
    alpha3: 'ATA',
    numeric: 10,
    dialCode: 672,
  },
  {
    name: 'Antigua and Barbuda',
    alpha2: 'AG',
    alpha3: 'ATG',
    numeric: 28,
    dialCode: '1-268',
  },
  {
    name: 'Argentina',
    alpha2: 'AR',
    alpha3: 'ARG',
    numeric: 32,
    dialCode: 54,
  },
  {
    name: 'Armenia',
    alpha2: 'AM',
    alpha3: 'ARM',
    numeric: 51,
    dialCode: 374,
  },
  {
    name: 'Aruba',
    alpha2: 'AW',
    alpha3: 'ABW',
    numeric: 533,
    dialCode: 297,
  },
  {
    name: 'Australia',
    alpha2: 'AU',
    alpha3: 'AUS',
    numeric: 36,
    dialCode: 61,
  },
  {
    name: 'Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    numeric: 40,
    dialCode: 43,
  },
  {
    name: 'Azerbaijan',
    alpha2: 'AZ',
    alpha3: 'AZE',
    numeric: 31,
    dialCode: 994,
  },
  {
    name: 'Bahamas',
    alpha2: 'BS',
    alpha3: 'BHS',
    numeric: 44,
    dialCode: '1-242',
  },
  {
    name: 'Bahrain',
    alpha2: 'BH',
    alpha3: 'BHR',
    numeric: 48,
    dialCode: 973,
  },
  {
    name: 'Bangladesh',
    alpha2: 'BD',
    alpha3: 'BGD',
    numeric: 50,
    dialCode: 880,
  },
  {
    name: 'Barbados',
    alpha2: 'BB',
    alpha3: 'BRB',
    numeric: 52,
    dialCode: '1-246',
  },
  {
    name: 'Belarus',
    alpha2: 'BY',
    alpha3: 'BLR',
    numeric: 112,
    dialCode: 375,
  },
  {
    name: 'Belgium',
    alpha2: 'BE',
    alpha3: 'BEL',
    numeric: 56,
    dialCode: 32,
  },
  {
    name: 'Belize',
    alpha2: 'BZ',
    alpha3: 'BLZ',
    numeric: 84,
    dialCode: 501,
  },
  {
    name: 'Benin',
    alpha2: 'BJ',
    alpha3: 'BEN',
    numeric: 204,
    dialCode: 229,
  },
  {
    name: 'Bermuda',
    alpha2: 'BM',
    alpha3: 'BMU',
    numeric: 60,
    dialCode: '1-441',
  },
  {
    name: 'Bhutan',
    alpha2: 'BT',
    alpha3: 'BTN',
    numeric: 64,
    dialCode: 975,
  },
  {
    name: 'Bolivia',
    alpha2: 'BO',
    alpha3: 'BOL',
    numeric: 68,
    dialCode: 591,
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2: 'BA',
    alpha3: 'BIH',
    numeric: 70,
    dialCode: 387,
  },
  {
    name: 'Botswana',
    alpha2: 'BW',
    alpha3: 'BWA',
    numeric: 72,
    dialCode: 267,
  },
  {
    name: 'Bouvet Island',
    alpha2: 'BV',
    alpha3: 'BVT',
    numeric: 74,
    dialCode: 47,
  },
  {
    name: 'Brazil',
    alpha2: 'BR',
    alpha3: 'BRA',
    numeric: 76,
    dialCode: 55,
  },
  {
    name: 'British Virgin Islands',
    alpha2: 'VG',
    alpha3: 'VGB',
    numeric: 92,
    dialCode: '1-284',
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2: 'IO',
    alpha3: 'IOT',
    numeric: 86,
    dialCode: 246,
  },
  {
    name: 'Brunei Darussalam',
    alpha2: 'BN',
    alpha3: 'BRN',
    numeric: 96,
    dialCode: 673,
  },
  {
    name: 'Bulgaria',
    alpha2: 'BG',
    alpha3: 'BGR',
    numeric: 100,
    dialCode: 359,
  },
  {
    name: 'Burkina Faso',
    alpha2: 'BF',
    alpha3: 'BFA',
    numeric: 854,
    dialCode: 226,
  },
  {
    name: 'Burundi',
    alpha2: 'BI',
    alpha3: 'BDI',
    numeric: 108,
    dialCode: 257,
  },
  {
    name: 'Cambodia',
    alpha2: 'KH',
    alpha3: 'KHM',
    numeric: 116,
    dialCode: 855,
  },
  {
    name: 'Cameroon',
    alpha2: 'CM',
    alpha3: 'CMR',
    numeric: 120,
    dialCode: 237,
  },
  {
    name: 'Canada',
    alpha2: 'CA',
    alpha3: 'CAN',
    numeric: 124,
    dialCode: 1,
  },
  {
    name: 'Cape Verde',
    alpha2: 'CV',
    alpha3: 'CPV',
    numeric: 132,
    dialCode: 238,
  },
  {
    name: 'Cayman Islands',
    alpha2: 'KY',
    alpha3: 'CYM',
    numeric: 136,
    dialCode: '1-345',
  },
  {
    name: 'Central African Republic',
    alpha2: 'CF',
    alpha3: 'CAF',
    numeric: 140,
    dialCode: 236,
  },
  {
    name: 'Chad',
    alpha2: 'TD',
    alpha3: 'TCD',
    numeric: 148,
    dialCode: 235,
  },
  {
    name: 'Chile',
    alpha2: 'CL',
    alpha3: 'CHL',
    numeric: 152,
    dialCode: 56,
  },
  {
    name: 'China',
    alpha2: 'CN',
    alpha3: 'CHN',
    numeric: 156,
    dialCode: 86,
  },
  {
    name: 'Hong Kong, SAR China',
    alpha2: 'HK',
    alpha3: 'HKG',
    numeric: 344,
    dialCode: 852,
  },
  {
    name: 'Macao, SAR China',
    alpha2: 'MO',
    alpha3: 'MAC',
    numeric: 446,
    dialCode: 853,
  },
  {
    name: 'Christmas Island',
    alpha2: 'CX',
    alpha3: 'CXR',
    numeric: 162,
    dialCode: 61,
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2: 'CC',
    alpha3: 'CCK',
    numeric: 166,
    dialCode: 61,
  },
  {
    name: 'Colombia',
    alpha2: 'CO',
    alpha3: 'COL',
    numeric: 170,
    dialCode: 57,
  },
  {
    name: 'Comoros',
    alpha2: 'KM',
    alpha3: 'COM',
    numeric: 174,
    dialCode: 269,
  },
  {
    name: 'Congo (Brazzaville)',
    alpha2: 'CG',
    alpha3: 'COG',
    numeric: 178,
    dialCode: 242,
  },
  {
    name: 'Congo, (Kinshasa)',
    alpha2: 'CD',
    alpha3: 'COD',
    numeric: 180,
    dialCode: 243,
  },
  {
    name: 'Cook Islands',
    alpha2: 'CK',
    alpha3: 'COK',
    numeric: 184,
    dialCode: 682,
  },
  {
    name: 'Costa Rica',
    alpha2: 'CR',
    alpha3: 'CRI',
    numeric: 188,
    dialCode: 506,
  },
  {
    name: 'Côte d\'Ivoire',
    alpha2: 'CI',
    alpha3: 'CIV',
    numeric: 384,
    dialCode: 225,
  },
  {
    name: 'Croatia',
    alpha2: 'HR',
    alpha3: 'HRV',
    numeric: 191,
    dialCode: 385,
  },
  {
    name: 'Cuba',
    alpha2: 'CU',
    alpha3: 'CUB',
    numeric: 192,
    dialCode: 53,
  },
  {
    name: 'Cyprus',
    alpha2: 'CY',
    alpha3: 'CYP',
    numeric: 196,
    dialCode: 357,
  },
  {
    name: 'Czech Republic',
    alpha2: 'CZ',
    alpha3: 'CZE',
    numeric: 203,
    dialCode: 420,
  },
  {
    name: 'Denmark',
    alpha2: 'DK',
    alpha3: 'DNK',
    numeric: 208,
    dialCode: 45,
  },
  {
    name: 'Djibouti',
    alpha2: 'DJ',
    alpha3: 'DJI',
    numeric: 262,
    dialCode: 253,
  },
  {
    name: 'Dominica',
    alpha2: 'DM',
    alpha3: 'DMA',
    numeric: 212,
    dialCode: '1-767',
  },
  {
    name: 'Dominican Republic',
    alpha2: 'DO',
    alpha3: 'DOM',
    numeric: 214,
    dialCode: '1-809,1-829,1-849',
  },
  {
    name: 'Ecuador',
    alpha2: 'EC',
    alpha3: 'ECU',
    numeric: 218,
    dialCode: 593,
  },
  {
    name: 'Egypt',
    alpha2: 'EG',
    alpha3: 'EGY',
    numeric: 818,
    dialCode: 20,
  },
  {
    name: 'El Salvador',
    alpha2: 'SV',
    alpha3: 'SLV',
    numeric: 222,
    dialCode: 503,
  },
  {
    name: 'Equatorial Guinea',
    alpha2: 'GQ',
    alpha3: 'GNQ',
    numeric: 226,
    dialCode: 240,
  },
  {
    name: 'Eritrea',
    alpha2: 'ER',
    alpha3: 'ERI',
    numeric: 232,
    dialCode: 291,
  },
  {
    name: 'Estonia',
    alpha2: 'EE',
    alpha3: 'EST',
    numeric: 233,
    dialCode: 372,
  },
  {
    name: 'Ethiopia',
    alpha2: 'ET',
    alpha3: 'ETH',
    numeric: 231,
    dialCode: 251,
  },
  {
    name: 'Falkland Islands (Malvinas)',
    alpha2: 'FK',
    alpha3: 'FLK',
    numeric: 238,
    dialCode: 500,
  },
  {
    name: 'Faroe Islands',
    alpha2: 'FO',
    alpha3: 'FRO',
    numeric: 234,
    dialCode: 298,
  },
  {
    name: 'Fiji',
    alpha2: 'FJ',
    alpha3: 'FJI',
    numeric: 242,
    dialCode: 679,
  },
  {
    name: 'Finland',
    alpha2: 'FI',
    alpha3: 'FIN',
    numeric: 246,
    dialCode: 358,
  },
  {
    name: 'France',
    alpha2: 'FR',
    alpha3: 'FRA',
    numeric: 250,
    dialCode: 33,
  },
  {
    name: 'French Guiana',
    alpha2: 'GF',
    alpha3: 'GUF',
    numeric: 254,
    dialCode: 594,
  },
  {
    name: 'French Polynesia',
    alpha2: 'PF',
    alpha3: 'PYF',
    numeric: 258,
    dialCode: 689,
  },
  {
    name: 'French Southern Territories',
    alpha2: 'TF',
    alpha3: 'ATF',
    numeric: 260,
    dialCode: 262,
  },
  {
    name: 'Gabon',
    alpha2: 'GA',
    alpha3: 'GAB',
    numeric: 266,
    dialCode: 241,
  },
  {
    name: 'Gambia',
    alpha2: 'GM',
    alpha3: 'GMB',
    numeric: 270,
    dialCode: 220,
  },
  {
    name: 'Georgia',
    alpha2: 'GE',
    alpha3: 'GEO',
    numeric: 268,
    dialCode: 995,
  },
  {
    name: 'Germany',
    alpha2: 'DE',
    alpha3: 'DEU',
    numeric: 276,
    dialCode: 49,
  },
  {
    name: 'Ghana',
    alpha2: 'GH',
    alpha3: 'GHA',
    numeric: 288,
    dialCode: 233,
  },
  {
    name: 'Gibraltar',
    alpha2: 'GI',
    alpha3: 'GIB',
    numeric: 292,
    dialCode: 350,
  },
  {
    name: 'Greece',
    alpha2: 'GR',
    alpha3: 'GRC',
    numeric: 300,
    dialCode: 30,
  },
  {
    name: 'Greenland',
    alpha2: 'GL',
    alpha3: 'GRL',
    numeric: 304,
    dialCode: 299,
  },
  {
    name: 'Grenada',
    alpha2: 'GD',
    alpha3: 'GRD',
    numeric: 308,
    dialCode: '1-473',
  },
  {
    name: 'Guadeloupe',
    alpha2: 'GP',
    alpha3: 'GLP',
    numeric: 312,
    dialCode: 590,
  },
  {
    name: 'Guam',
    alpha2: 'GU',
    alpha3: 'GUM',
    numeric: 316,
    dialCode: '1-671',
  },
  {
    name: 'Guatemala',
    alpha2: 'GT',
    alpha3: 'GTM',
    numeric: 320,
    dialCode: 502,
  },
  {
    name: 'Guernsey',
    alpha2: 'GG',
    alpha3: 'GGY',
    numeric: 831,
    dialCode: 44,
  },
  {
    name: 'Guinea',
    alpha2: 'GN',
    alpha3: 'GIN',
    numeric: 324,
    dialCode: 224,
  },
  {
    name: 'Guinea-Bissau',
    alpha2: 'GW',
    alpha3: 'GNB',
    numeric: 624,
    dialCode: 245,
  },
  {
    name: 'Guyana',
    alpha2: 'GY',
    alpha3: 'GUY',
    numeric: 328,
    dialCode: 592,
  },
  {
    name: 'Haiti',
    alpha2: 'HT',
    alpha3: 'HTI',
    numeric: 332,
    dialCode: 509,
  },
  {
    name: 'Heard and Mcdonald Islands',
    alpha2: 'HM',
    alpha3: 'HMD',
    numeric: 334,
    dialCode: 672,
  },
  {
    name: 'Holy See (Vatican City State)',
    alpha2: 'VA',
    alpha3: 'VAT',
    numeric: 336,
    dialCode: 379,
  },
  {
    name: 'Honduras',
    alpha2: 'HN',
    alpha3: 'HND',
    numeric: 340,
    dialCode: 504,
  },
  {
    name: 'Hungary',
    alpha2: 'HU',
    alpha3: 'HUN',
    numeric: 348,
    dialCode: 36,
  },
  {
    name: 'Iceland',
    alpha2: 'IS',
    alpha3: 'ISL',
    numeric: 352,
    dialCode: 354,
  },
  {
    name: 'India',
    alpha2: 'IN',
    alpha3: 'IND',
    numeric: 356,
    dialCode: 91,
  },
  {
    name: 'Indonesia',
    alpha2: 'ID',
    alpha3: 'IDN',
    numeric: 360,
    dialCode: 62,
  },
  {
    name: 'Iran, Islamic Republic of',
    alpha2: 'IR',
    alpha3: 'IRN',
    numeric: 364,
    dialCode: 98,
  },
  {
    name: 'Iraq',
    alpha2: 'IQ',
    alpha3: 'IRQ',
    numeric: 368,
    dialCode: 964,
  },
  {
    name: 'Ireland',
    alpha2: 'IE',
    alpha3: 'IRL',
    numeric: 372,
    dialCode: 353,
  },
  {
    name: 'Isle of Man',
    alpha2: 'IM',
    alpha3: 'IMN',
    numeric: 833,
    dialCode: 44,
  },
  {
    name: 'Israel',
    alpha2: 'IL',
    alpha3: 'ISR',
    numeric: 376,
    dialCode: 972,
  },
  {
    name: 'Italy',
    alpha2: 'IT',
    alpha3: 'ITA',
    numeric: 380,
    dialCode: 39,
  },
  {
    name: 'Jamaica',
    alpha2: 'JM',
    alpha3: 'JAM',
    numeric: 388,
    dialCode: '1-876',
  },
  {
    name: 'Japan',
    alpha2: 'JP',
    alpha3: 'JPN',
    numeric: 392,
    dialCode: 81,
  },
  {
    name: 'Jersey',
    alpha2: 'JE',
    alpha3: 'JEY',
    numeric: 832,
    dialCode: 44,
  },
  {
    name: 'Jordan',
    alpha2: 'JO',
    alpha3: 'JOR',
    numeric: 400,
    dialCode: 962,
  },
  {
    name: 'Kazakhstan',
    alpha2: 'KZ',
    alpha3: 'KAZ',
    numeric: 398,
    dialCode: 7,
  },
  {
    name: 'Kenya',
    alpha2: 'KE',
    alpha3: 'KEN',
    numeric: 404,
    dialCode: 254,
  },
  {
    name: 'Kiribati',
    alpha2: 'KI',
    alpha3: 'KIR',
    numeric: 296,
    dialCode: 686,
  },
  {
    name: 'Korea (North)',
    alpha2: 'KP',
    alpha3: 'PRK',
    numeric: 408,
    dialCode: 850,
  },
  {
    name: 'Korea (South)',
    alpha2: 'KR',
    alpha3: 'KOR',
    numeric: 410,
    dialCode: 82,
  },
  { // temporary, not in ISO 3166
    name: 'Kosovo',
    alpha2: 'XK',
    alpha3: 'XKX',
    numeric: 926,
    dialCode: 383,
  },
  { // temporary, not in ISO 3166
    name: 'Kosovo',
    alpha2: 'XK',
    alpha3: 'XKS',
    numeric: 926,
    dialCode: 383,
  },
  {
    name: 'Kuwait',
    alpha2: 'KW',
    alpha3: 'KWT',
    numeric: 414,
    dialCode: 965,
  },
  {
    name: 'Kyrgyzstan',
    alpha2: 'KG',
    alpha3: 'KGZ',
    numeric: 417,
    dialCode: 996,
  },
  {
    name: 'Lao PDR',
    alpha2: 'LA',
    alpha3: 'LAO',
    numeric: 418,
    dialCode: 856,
  },
  {
    name: 'Latvia',
    alpha2: 'LV',
    alpha3: 'LVA',
    numeric: 428,
    dialCode: 371,
  },
  {
    name: 'Lebanon',
    alpha2: 'LB',
    alpha3: 'LBN',
    numeric: 422,
    dialCode: 961,
  },
  {
    name: 'Lesotho',
    alpha2: 'LS',
    alpha3: 'LSO',
    numeric: 426,
    dialCode: 266,
  },
  {
    name: 'Liberia',
    alpha2: 'LR',
    alpha3: 'LBR',
    numeric: 430,
    dialCode: 231,
  },
  {
    name: 'Libya',
    alpha2: 'LY',
    alpha3: 'LBY',
    numeric: 434,
    dialCode: 218,
  },
  {
    name: 'Liechtenstein',
    alpha2: 'LI',
    alpha3: 'LIE',
    numeric: 438,
    dialCode: 423,
  },
  {
    name: 'Lithuania',
    alpha2: 'LT',
    alpha3: 'LTU',
    numeric: 440,
    dialCode: 370,
  },
  {
    name: 'Luxembourg',
    alpha2: 'LU',
    alpha3: 'LUX',
    numeric: 442,
    dialCode: 352,
  },
  {
    name: 'Macedonia, Republic of',
    alpha2: 'MK',
    alpha3: 'MKD',
    numeric: 807,
    dialCode: 389,
  },
  {
    name: 'Madagascar',
    alpha2: 'MG',
    alpha3: 'MDG',
    numeric: 450,
    dialCode: 261,
  },
  {
    name: 'Malawi',
    alpha2: 'MW',
    alpha3: 'MWI',
    numeric: 454,
    dialCode: 265,
  },
  {
    name: 'Malaysia',
    alpha2: 'MY',
    alpha3: 'MYS',
    numeric: 458,
    dialCode: 60,
  },
  {
    name: 'Maldives',
    alpha2: 'MV',
    alpha3: 'MDV',
    numeric: 462,
    dialCode: 960,
  },
  {
    name: 'Mali',
    alpha2: 'ML',
    alpha3: 'MLI',
    numeric: 466,
    dialCode: 223,
  },
  {
    name: 'Malta',
    alpha2: 'MT',
    alpha3: 'MLT',
    numeric: 470,
    dialCode: 356,
  },
  {
    name: 'Marshall Islands',
    alpha2: 'MH',
    alpha3: 'MHL',
    numeric: 584,
    dialCode: 692,
  },
  {
    name: 'Martinique',
    alpha2: 'MQ',
    alpha3: 'MTQ',
    numeric: 474,
    dialCode: 596,
  },
  {
    name: 'Mauritania',
    alpha2: 'MR',
    alpha3: 'MRT',
    numeric: 478,
    dialCode: 222,
  },
  {
    name: 'Mauritius',
    alpha2: 'MU',
    alpha3: 'MUS',
    numeric: 480,
    dialCode: 230,
  },
  {
    name: 'Mayotte',
    alpha2: 'YT',
    alpha3: 'MYT',
    numeric: 175,
    dialCode: 262,
  },
  {
    name: 'Mexico',
    alpha2: 'MX',
    alpha3: 'MEX',
    numeric: 484,
    dialCode: 52,
  },
  {
    name: 'Micronesia, Federated States of',
    alpha2: 'FM',
    alpha3: 'FSM',
    numeric: 583,
    dialCode: 691,
  },
  {
    name: 'Moldova, Republic of',
    alpha2: 'MD',
    alpha3: 'MDA',
    numeric: 498,
    dialCode: 373,
  },
  {
    name: 'Monaco',
    alpha2: 'MC',
    alpha3: 'MCO',
    numeric: 492,
    dialCode: 377,
  },
  {
    name: 'Mongolia',
    alpha2: 'MN',
    alpha3: 'MNG',
    numeric: 496,
    dialCode: 976,
  },
  {
    name: 'Montenegro',
    alpha2: 'ME',
    alpha3: 'MNE',
    numeric: 499,
    dialCode: 382,
  },
  {
    name: 'Montserrat',
    alpha2: 'MS',
    alpha3: 'MSR',
    numeric: 500,
    dialCode: '1-664',
  },
  {
    name: 'Morocco',
    alpha2: 'MA',
    alpha3: 'MAR',
    numeric: 504,
    dialCode: 212,
  },
  {
    name: 'Mozambique',
    alpha2: 'MZ',
    alpha3: 'MOZ',
    numeric: 508,
    dialCode: 258,
  },
  {
    name: 'Myanmar',
    alpha2: 'MM',
    alpha3: 'MMR',
    numeric: 104,
    dialCode: 95,
  },
  {
    name: 'Namibia',
    alpha2: 'NA',
    alpha3: 'NAM',
    numeric: 516,
    dialCode: 264,
  },
  {
    name: 'Nauru',
    alpha2: 'NR',
    alpha3: 'NRU',
    numeric: 520,
    dialCode: 674,
  },
  {
    name: 'Nepal',
    alpha2: 'NP',
    alpha3: 'NPL',
    numeric: 524,
    dialCode: 977,
  },
  {
    name: 'Netherlands',
    alpha2: 'NL',
    alpha3: 'NLD',
    numeric: 528,
    dialCode: 31,
  },
  {
    name: 'Netherlands Antilles',
    alpha2: 'AN',
    alpha3: 'ANT',
    numeric: 530,
    dialCode: 599,
  },
  {
    name: 'New Caledonia',
    alpha2: 'NC',
    alpha3: 'NCL',
    numeric: 540,
    dialCode: 687,
  },
  {
    name: 'New Zealand',
    alpha2: 'NZ',
    alpha3: 'NZL',
    numeric: 554,
    dialCode: 64,
  },
  {
    name: 'Nicaragua',
    alpha2: 'NI',
    alpha3: 'NIC',
    numeric: 558,
    dialCode: 505,
  },
  {
    name: 'Niger',
    alpha2: 'NE',
    alpha3: 'NER',
    numeric: 562,
    dialCode: 227,
  },
  {
    name: 'Nigeria',
    alpha2: 'NG',
    alpha3: 'NGA',
    numeric: 566,
    dialCode: 234,
  },
  {
    name: 'Niue',
    alpha2: 'NU',
    alpha3: 'NIU',
    numeric: 570,
    dialCode: 683,
  },
  {
    name: 'Norfolk Island',
    alpha2: 'NF',
    alpha3: 'NFK',
    numeric: 574,
    dialCode: 672,
  },
  {
    name: 'Northern Mariana Islands',
    alpha2: 'MP',
    alpha3: 'MNP',
    numeric: 580,
    dialCode: '1-670',
  },
  {
    name: 'Norway',
    alpha2: 'NO',
    alpha3: 'NOR',
    numeric: 578,
    dialCode: 47,
  },
  {
    name: 'Oman',
    alpha2: 'OM',
    alpha3: 'OMN',
    numeric: 512,
    dialCode: 968,
  },
  {
    name: 'Pakistan',
    alpha2: 'PK',
    alpha3: 'PAK',
    numeric: 586,
    dialCode: 92,
  },
  {
    name: 'Palau',
    alpha2: 'PW',
    alpha3: 'PLW',
    numeric: 585,
    dialCode: 680,
  },
  {
    name: 'Palestinian Territory',
    alpha2: 'PS',
    alpha3: 'PSE',
    numeric: 275,
    dialCode: 970,
  },
  {
    name: 'Panama',
    alpha2: 'PA',
    alpha3: 'PAN',
    numeric: 591,
    dialCode: 507,
  },
  {
    name: 'Papua New Guinea',
    alpha2: 'PG',
    alpha3: 'PNG',
    numeric: 598,
    dialCode: 675,
  },
  {
    name: 'Paraguay',
    alpha2: 'PY',
    alpha3: 'PRY',
    numeric: 600,
    dialCode: 595,
  },
  {
    name: 'Peru',
    alpha2: 'PE',
    alpha3: 'PER',
    numeric: 604,
    dialCode: 51,
  },
  {
    name: 'Philippines',
    alpha2: 'PH',
    alpha3: 'PHL',
    numeric: 608,
    dialCode: 63,
  },
  {
    name: 'Pitcairn',
    alpha2: 'PN',
    alpha3: 'PCN',
    numeric: 612,
    dialCode: 870,
  },
  {
    name: 'Poland',
    alpha2: 'PL',
    alpha3: 'POL',
    numeric: 616,
    dialCode: 48,
  },
  {
    name: 'Portugal',
    alpha2: 'PT',
    alpha3: 'PRT',
    numeric: 620,
    dialCode: 351,
  },
  {
    name: 'Puerto Rico',
    alpha2: 'PR',
    alpha3: 'PRI',
    numeric: 630,
    dialCode: 1,
  },
  {
    name: 'Qatar',
    alpha2: 'QA',
    alpha3: 'QAT',
    numeric: 634,
    dialCode: 974,
  },
  {
    name: 'Réunion',
    alpha2: 'RE',
    alpha3: 'REU',
    numeric: 638,
    dialCode: 262,
  },
  {
    name: 'Romania',
    alpha2: 'RO',
    alpha3: 'ROU',
    numeric: 642,
    dialCode: 40,
  },
  {
    name: 'Russian Federation',
    alpha2: 'RU',
    alpha3: 'RUS',
    numeric: 643,
    dialCode: 7,
  },
  {
    name: 'Rwanda',
    alpha2: 'RW',
    alpha3: 'RWA',
    numeric: 646,
    dialCode: 250,
  },
  {
    name: 'Saint-Barthélemy',
    alpha2: 'BL',
    alpha3: 'BLM',
    numeric: 652,
    dialCode: 590,
  },
  {
    name: 'Saint Helena',
    alpha2: 'SH',
    alpha3: 'SHN',
    numeric: 654,
    dialCode: 290,
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2: 'KN',
    alpha3: 'KNA',
    numeric: 659,
    dialCode: '1-869',
  },
  {
    name: 'Saint Lucia',
    alpha2: 'LC',
    alpha3: 'LCA',
    numeric: 662,
    dialCode: '1-758',
  },
  {
    name: 'Saint-Martin (French)',
    alpha2: 'MF',
    alpha3: 'MAF',
    numeric: 663,
    dialCode: 590,
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2: 'PM',
    alpha3: 'SPM',
    numeric: 666,
    dialCode: 508,
  },
  {
    name: 'Saint Vincent and Grenadines',
    alpha2: 'VC',
    alpha3: 'VCT',
    numeric: 670,
    dialCode: '1-784',
  },
  {
    name: 'Samoa',
    alpha2: 'WS',
    alpha3: 'WSM',
    numeric: 882,
    dialCode: 685,
  },
  {
    name: 'San Marino',
    alpha2: 'SM',
    alpha3: 'SMR',
    numeric: 674,
    dialCode: 378,
  },
  {
    name: 'Sao Tome and Principe',
    alpha2: 'ST',
    alpha3: 'STP',
    numeric: 678,
    dialCode: 239,
  },
  {
    name: 'Saudi Arabia',
    alpha2: 'SA',
    alpha3: 'SAU',
    numeric: 682,
    dialCode: 966,
  },
  {
    name: 'Senegal',
    alpha2: 'SN',
    alpha3: 'SEN',
    numeric: 686,
    dialCode: 221,
  },
  {
    name: 'Serbia',
    alpha2: 'RS',
    alpha3: 'SRB',
    numeric: 688,
    dialCode: 381,
  },
  {
    name: 'Seychelles',
    alpha2: 'SC',
    alpha3: 'SYC',
    numeric: 690,
    dialCode: 248,
  },
  {
    name: 'Sierra Leone',
    alpha2: 'SL',
    alpha3: 'SLE',
    numeric: 694,
    dialCode: 232,
  },
  {
    name: 'Singapore',
    alpha2: 'SG',
    alpha3: 'SGP',
    numeric: 702,
    dialCode: 65,
  },
  {
    name: 'Slovakia',
    alpha2: 'SK',
    alpha3: 'SVK',
    numeric: 703,
    dialCode: 421,
  },
  {
    name: 'Slovenia',
    alpha2: 'SI',
    alpha3: 'SVN',
    numeric: 705,
    dialCode: 386,
  },
  {
    name: 'Solomon Islands',
    alpha2: 'SB',
    alpha3: 'SLB',
    numeric: 90,
    dialCode: 677,
  },
  {
    name: 'Somalia',
    alpha2: 'SO',
    alpha3: 'SOM',
    numeric: 706,
    dialCode: 252,
  },
  {
    name: 'South Africa',
    alpha2: 'ZA',
    alpha3: 'ZAF',
    numeric: 710,
    dialCode: 27,
  },
  {
    name: 'South Georgia and the\nSouth Sandwich Islands',
    alpha2: 'GS',
    alpha3: 'SGS',
    numeric: 239,
    dialCode: 500,
  },
  {
    name: 'South Sudan',
    alpha2: 'SS',
    alpha3: 'SSD',
    numeric: 728,
    dialCode: 211,
  },
  {
    name: 'Spain',
    alpha2: 'ES',
    alpha3: 'ESP',
    numeric: 724,
    dialCode: 34,
  },
  {
    name: 'Sri Lanka',
    alpha2: 'LK',
    alpha3: 'LKA',
    numeric: 144,
    dialCode: 94,
  },
  {
    name: 'Sudan',
    alpha2: 'SD',
    alpha3: 'SDN',
    numeric: 736,
    dialCode: 249,
  },
  {
    name: 'Suriname',
    alpha2: 'SR',
    alpha3: 'SUR',
    numeric: 740,
    dialCode: 597,
  },
  {
    name: 'Svalbard and Jan Mayen Islands',
    alpha2: 'SJ',
    alpha3: 'SJM',
    numeric: 744,
    dialCode: 47,
  },
  {
    name: 'Swaziland',
    alpha2: 'SZ',
    alpha3: 'SWZ',
    numeric: 748,
    dialCode: 268,
  },
  {
    name: 'Sweden',
    alpha2: 'SE',
    alpha3: 'SWE',
    numeric: 752,
    dialCode: 46,
  },
  {
    name: 'Switzerland',
    alpha2: 'CH',
    alpha3: 'CHE',
    numeric: 756,
    dialCode: 41,
  },
  {
    name: 'Syrian Arab Republic (Syria)',
    alpha2: 'SY',
    alpha3: 'SYR',
    numeric: 760,
    dialCode: 963,
  },
  {
    name: 'Taiwan, Republic of China',
    alpha2: 'TW',
    alpha3: 'TWN',
    numeric: 158,
    dialCode: 886,
  },
  {
    name: 'Tajikistan',
    alpha2: 'TJ',
    alpha3: 'TJK',
    numeric: 762,
    dialCode: 992,
  },
  {
    name: 'Tanzania, United Republic of',
    alpha2: 'TZ',
    alpha3: 'TZA',
    numeric: 834,
    dialCode: 255,
  },
  {
    name: 'Thailand',
    alpha2: 'TH',
    alpha3: 'THA',
    numeric: 764,
    dialCode: 66,
  },
  {
    name: 'Timor-Leste',
    alpha2: 'TL',
    alpha3: 'TLS',
    numeric: 626,
    dialCode: 670,
  },
  {
    name: 'Togo',
    alpha2: 'TG',
    alpha3: 'TGO',
    numeric: 768,
    dialCode: 228,
  },
  {
    name: 'Tokelau',
    alpha2: 'TK',
    alpha3: 'TKL',
    numeric: 772,
    dialCode: 690,
  },
  {
    name: 'Tonga',
    alpha2: 'TO',
    alpha3: 'TON',
    numeric: 776,
    dialCode: 676,
  },
  {
    name: 'Trinidad and Tobago',
    alpha2: 'TT',
    alpha3: 'TTO',
    numeric: 780,
    dialCode: '1-868',
  },
  {
    name: 'Tunisia',
    alpha2: 'TN',
    alpha3: 'TUN',
    numeric: 788,
    dialCode: 216,
  },
  {
    name: 'Turkey',
    alpha2: 'TR',
    alpha3: 'TUR',
    numeric: 792,
    dialCode: 90,
  },
  {
    name: 'Turkmenistan',
    alpha2: 'TM',
    alpha3: 'TKM',
    numeric: 795,
    dialCode: 993,
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2: 'TC',
    alpha3: 'TCA',
    numeric: 796,
    dialCode: '1-649',
  },
  {
    name: 'Tuvalu',
    alpha2: 'TV',
    alpha3: 'TUV',
    numeric: 798,
    dialCode: 688,
  },
  {
    name: 'Uganda',
    alpha2: 'UG',
    alpha3: 'UGA',
    numeric: 800,
    dialCode: 256,
  },
  {
    name: 'Ukraine',
    alpha2: 'UA',
    alpha3: 'UKR',
    numeric: 804,
    dialCode: 380,
  },
  {
    name: 'United Arab Emirates',
    alpha2: 'AE',
    alpha3: 'ARE',
    numeric: 784,
    dialCode: 971,
  },
  {
    name: 'United Kingdom',
    alpha2: 'GB',
    alpha3: 'GBR',
    numeric: 826,
    dialCode: 44,
  },
  {
    name: 'United States of America',
    alpha2: 'US',
    alpha3: 'USA',
    numeric: 840,
    dialCode: 1,
  },
  {
    name: 'US Minor Outlying Islands',
    alpha2: 'UM',
    alpha3: 'UMI',
    numeric: 581,
    dialCode: 1,
  },
  {
    name: 'Uruguay',
    alpha2: 'UY',
    alpha3: 'URY',
    numeric: 858,
    dialCode: 598,
  },
  {
    name: 'Uzbekistan',
    alpha2: 'UZ',
    alpha3: 'UZB',
    numeric: 860,
    dialCode: 998,
  },
  {
    name: 'Vanuatu',
    alpha2: 'VU',
    alpha3: 'VUT',
    numeric: 548,
    dialCode: 678,
  },
  {
    name: 'Venezuela (Bolivarian Republic)',
    alpha2: 'VE',
    alpha3: 'VEN',
    numeric: 862,
    dialCode: 58,
  },
  {
    name: 'Viet Nam',
    alpha2: 'VN',
    alpha3: 'VNM',
    numeric: 704,
    dialCode: 84,
  },
  {
    name: 'Virgin Islands, US',
    alpha2: 'VI',
    alpha3: 'VIR',
    numeric: 850,
    dialCode: '1-340',
  },
  {
    name: 'Wallis and Futuna Islands',
    alpha2: 'WF',
    alpha3: 'WLF',
    numeric: 876,
    dialCode: 681,
  },
  {
    name: 'Western Sahara',
    alpha2: 'EH',
    alpha3: 'ESH',
    numeric: 732,
    dialCode: 212,
  },
  {
    name: 'Yemen',
    alpha2: 'YE',
    alpha3: 'YEM',
    numeric: 887,
    dialCode: 967,
  },
  {
    name: 'Zambia',
    alpha2: 'ZM',
    alpha3: 'ZMB',
    numeric: 894,
    dialCode: 260,
  },
  {
    name: 'Zimbabwe',
    alpha2: 'ZW',
    alpha3: 'ZWE',
    numeric: 716,
    dialCode: 263,
  },
];

export const COUNTRIES_IN_NUMERIC = COUNTRY_CODES.map((c) => c.numeric);
export const COUNTRIES_IN_ALPHA2 = COUNTRY_CODES.map((c) => c.alpha2);
export const COUNTRIES_IN_ALPHA3 = COUNTRY_CODES.map((c) => c.alpha3);
export const COUNTRIES_IN_DIAL = COUNTRY_CODES.map((c) => c.dialCode);

export const COUNTRY_CODES_NUMERIC = keyByForLoop(COUNTRY_CODES, (c) => c.numeric);
export const COUNTRY_CODES_ALPHA2 = keyByForLoop(COUNTRY_CODES, (c) => c.alpha2);
export const COUNTRY_CODES_ALPHA3 = keyByForLoop(COUNTRY_CODES, (c) => c.alpha3);
export const COUNTRY_CODES_DIAL = keyByForLoop(COUNTRY_CODES, (c) => c.dialCode);

// module.exports = {
//   COUNTRIES_IN_NUMERIC,
//   COUNTRIES_IN_ALPHA2,
//   COUNTRIES_IN_ALPHA3,
//   COUNTRIES_IN_DIAL,
//   COUNTRY_CODES_NUMERIC,
//   COUNTRY_CODES_ALPHA2,
//   COUNTRY_CODES_ALPHA3,
//   COUNTRY_CODES_DIAL,
// };
